export const BikeBrandList = {
  TVS: [
    'TVS Apache RTR 160',
    'TVS Apache RTR 160 4V',
    'TVS Apache RTR 200 4V',
    'TVS Apache RTR 310',
    'TVS N torque 125',
    'TVS Jupiter',
    'TVS Scooty Pep Plus',
    'TVS Sport',
    'TVS Jupiter 125',
    'TVS Star City Plus',
    'TVS Radeon',
    'TVS Scooty Zest 110',
    'TVS XL 100 Comfort',
    'TVS XL Heavy Duty',
    'TVS I qube',
    'TVS Wego',
    'TVS Victor',
    'TVS Phoenix',
  ],
  Yamaha: [
    'Yamaha YZF R15 V4',
    'Yamaha FZS F1',
    'Yamaha MT 15',
    'Yamaha FZ X',
    'Yamaha Ray ZR 125',
    'Yamaha FZ F1',
    'Yamaha Aerox 155',
    'Yamaha Fascino',
  ],
  Hero: [
    'Hero Splendor Plus',
    'Hero HF Deluxe',
    'Hero Glamour',
    'Hero Xtreme 160 R ',
    'Hero Passion Pro',
    'Hero Super Splendor',
    'Hero Xpulse 200 4V',
    'Hero Pleasure Plus',
    'Hero Xpulse 200',
    'Hero Maestro Edge 125',
    'Hero Xtreme 200 S',
    'Hero Xpulse 200 T',
    'Hero Splendor I Smart 110',
    'Hero Destini 125',
    'Hero Maestro Edge 110',
  ],
  'Royal Enfield': [
    'Royal Enfield Classic 350',
    'Royal Enfield Meteor 350',
    'Royal Enfield Bullet 350',
    'Royal Enfield Himalayan',
    'Royal Enfield Continental GT 650',
  ],
  Honda: [
    'Honda Activa 6 G',
    'Honda Hness CB 350',
    'Honda Shine',
    'Honda Hornet 2.0',
    'Honda Unicorn',
    'Honda Dio',
    'Honda Activa 125',
    'Honda X Blade',
    'Honda CB 350 RS',
    'Honda CB 200 X',
    'Honda Livo',
    'Honda Grazia',
    'Honda CD 110 Dream',
    'Honda CBR 650 R',
    'Honda Gold Wing',
    'Honda CB 650 R',
    'Honda CB 500 X',
    'Honda Africa Twin',
  ],
  Bajaj: [
    'Bajaj Pulsar N 250',
    'Bajaj Pulsar 125',

    'Bajaj Pulsar 150',

    'Bajaj Pulsar F 250',

    'Bajaj Pulsar NS 125',

    'Bajaj Pulsar NS 200',

    'Bajaj Platina 100',

    'Bajaj Pulsar NS 160',

    'Bajaj Pulsar RS 200',

    'Bajaj Pulsar 220 F',
    'Bajaj Pulsar Dominar 250',

    'Bajaj CT 100',

    'Bajaj Dominar 400',

    'Bajaj Chetak',
    'Bajaj Platina 110',

    'Bajaj CT 110',
    'Bajaj Avenger Street 160',

    'Bajaj Avenger Cruise 220',

    'Bajaj Pulsar 180',
  ],
  SUZUKI: [
    'SUZUKI Avenis 125',
    'SUZUKI Access 125',

    'SUZUKI Gixxer SF',

    'SUZUKI Burgman Street 125',

    'SUZUKI Gixxer',

    'SUZUKI Gixxer SF 250',

    'SUZUKI Hayabusa',

    'SUZUKI Intruder 150',

    'SUZUKI Gixxer 250 ',

    'SUZUKI V Strom 650 GT',
  ],
  KAWASAKI: [
    'KAWASAKI Ninja 1000',
    'KAWASAKI Ninja 300',
    'KAWASAKI Ninja 650',
    'KAWASAKI Ninja H2R',
    'KAWASAKI Ninja Z900',
    'KAWASAKI Ninja ZX 10 R',
    'KAWASAKI Ninja Z650',
    'KAWASAKI Vulcan S',
    'KAWASAKI Ninja ZH2',
    'KAWASAKI Ninja Z 650 RS',
    'KAWASAKI Versys 650',
    'KAWASAKI KX 250',
    'KAWASAKI Ninja W 800',

    'KAWASAKI Versys 1000',

    'KAWASAKI KX 450',
  ],
  BMW: [
    'BWM G 310 R',
    'BMW G 310 GS',
    'BMW M 1000 RR',
    'BMW R 1250 GS Adventure',
    'BMW S 1000 R',
    'BMW C 400 GT',
    'BMW R 18',
    'BMW R Nine T',
    'BMW F 900 R',
    'BMW R 1250 GS',
    'BMW R Nine T Scrambler',
    'BMW S 1000 XR',
    'BMW F 900 XR',
  ],
};

export const CarBrandList = {
  'MARUTI SUZUKI': [
    'MARUTI SUZUKI Swift',
    'MARUTI SUZUKI Ertiga',
    'MARUTI SUZUKI Baleno',
    'MARUTI SUZUKI Wagon R',
    'MARUTI SUZUKI Alto',
    'MARUTI SUZUKI XL 6',
    'MARUTI Vitara Brezza',
    'MARUTI Dzire',
    'MARUTI Celerio',
    'MARUTI S - Presso',
    'MARUTI Ignis',
    'MARUTI Ciaz',
    'MARUTI Vitara Brezza 2022',
    'MARUTI Jimmy',
    'MARUTI S - Cross 2022',
  ],
  Hyndai: [
    'HYUNDAI Creta',
    'HYUNDAI Venue',
    'HYUNDAI Grand i10 Nios',
    'HYUNDAI i20',
    'HYUNDAI Verna',
    'HYUNDAI Aura',
    'HYUNDAI Santro',
    'Alcazar',
    'Elantra',
    'i20 N Line ',
    'Tucson',
    'Kona Facelift',
    'Venue Facelift',
    'Creta Facelift',
    'New Tucson',
    'Casper',
    'New Elantra',
    'Ioniq',
    'New Kona',
  ],
  'Tata Cars': [
    'Nexon EV Max',
    'Nexon',
    'Altroz',
    'Punch',
    'Tiago',
    'Safari',
    'Harrier',
    'Tigor',
    'Nexon EV',
    'Tigor EV',
    'Tigor NRG',
    'Altroz EV',
    'Tiago EV',
    'CURVV EV Concept',
    'Avinga Concept',
  ],
  'Mahindra Cars': [
    'XUV 700',
    'XUV 300',
    'Thar',
    'Scorpio',
    'Balero Neo',
    'Bolero',
    'Marazzo',
    'Alturas G4',
    'KUV 100 NXT',
    'e KUV 100',
    'e XUV 300',
    'New Scorpio',
  ],
  Ferrari: [
    'FERRARI 812',
    'FERRARI Roma',
    'FERRARI Portofino  Facelift',
    'FERRARI F8 Tributo',
    'FERRARI Portofino',
    'FERRARI Purosangue SUV',
    'BENTLEY BENTAYGA',
    'CITROGEN CARS',
    'CITROGEN C5 Aircross CITROGEN C3',
    'ISUZU CARS',
    'ISUZU D - Max',
    'ISUZU MU-X',
    'MEAN METAL MOTORS AZANI',
    'DATSUN CARS',
    'DATSON GO+',
    'DATSON redi - GO',
    'DATSON GO',
    'MCLAREN CARS',
    'MCLAREN 720S MCLAREN GT',
    'FORCE MOTORS GURKHA',
    'FISKER OCEAN EV',
    'HAVAL H6',
    'ASTRON MARTIN CARS',
    'ASTRON MARTIN Martin DB 11',
    'ASTRON MARTIN Vantage',
  ],
  Mini: [
    'MINI Cooper',
    'MINI Countryman',
    'MINI Cooper SE',
    'MINI Cooper Convertible',
    'MINI  Cooper JCW',
  ],
  Lexus: [
    'LEXUS ES',
    'LEXUS LX',
    'LEXUS NX',
    'LEXUS LS',
    'LEXUS LC 500h',
    'LEXUS RX',
  ],
  Tesla: ['TESLA Model S'],
  Porsche: [
    'PORSCHE Cayenne',
    'PORSCHE Macan',
    'PORSCHE Cayenne Coupe',
    'PORSCHE 911',
    'PORSCHE 718',
    'PORSCHE Taycan Cross Turismo',
    'PORSCHE Taycan',
    'PORSCHE Panamera',
  ],
  Lamborghini: [
    'LAMBORGHINI Urus',
    'LAMBORGHINI Huracan Evo',
    'LAMBORGHINI Huracan STO',
    'LAMBORGHINI Huracan EVO SYPDER',
    'LAMBORGHINI Urus Facelift',
  ],
  'Rolls-Royce': [
    'ROLLS-ROYCE Phantom VIII',
    'ROLLS - ROYCE Wraith',
    'ROLLS - ROYCE Cullinan',
    'ROLLS - ROYCE Dawn',
    'ROLLS - ROYCE New Ghost',
  ],
  Nissan: ['NISSAN Magnite', 'NISSAN Kicks', 'NISSAN FT - R'],
  Volco: [
    'VOLVO XC40',
    'VOLVO XC90',
    'VOLCO S60',
    'VOLCO S90',
    'VOLCO XC60',
    'VOLCO XC40 Recharge',
  ],
  Ford: ['FORD Endeavour', 'FORD Ecosport', 'FORD Figo', 'FORD Aspire'],
  Jaguar: [
    'JAGUAR XE',
    'JAGUAR XF',
    'JAGUAR F- Pace',
    'JAGUAR F- Type',
    'JAGUAR I- Pace',
    'JAGUAR E- Pace',
  ],
  'Land Rover': [
    'LAND ROVER Velar',
    'LAND ROVER Range Rover',
    'LAND ROVER Evoque',
    'LAND ROVER Discovery',
    'LAND ROVER Discovery Sport',
    'LAND ROVER Sport',
    'LAND ROVER Defender',
    'LAND ROVER New Range Rover',
  ],
  Audi: [
    'AUDI Q2',
    'AUDI A4',
    'AUDI A6',
    'AUDI Q7',
    'AUDI Q5',
    'AUDI RS 7 Sportback',
    'AUDI Q8',
    'AUDI e- tron GT',
    'AUDI A8 L',
    'AUDI RS QB',
    'AUDI S5 Sportback',
    'AUDI e-tron',
    'AUDI RS 5',
    'AUDI e-tron Sportback',
    'AUDI New Q3',
    'AUDI New A3',
  ],
  Renault: [
    'RENAULT kiger',
    'RENAULT Kwid',
    'RENAULT Triber',
    'RENAULT City K - ZE',
  ],
  Jeep: ['JEEP Compass', 'JEEP Wrangler', 'JEEP Meridian'],
  Mg: [
    'MG Astor',
    'MG Hector',
    'MG GIO',
    'MG Hector Plus',
    'MG ZS EV',
    'MG Gloster',
    'MG ZS EV Excite',
  ],
  Volkswagon: [
    'VOLKSWAGON Taigun',
    'VOLKSWAGON Polo',
    'VOLKSWAGON Vento',
    'VOLKSWAGON Virtus',
  ],
  Kia: ['Carens', 'Seltos', 'Sonet', 'Carnival', 'EV6'],
  Toyota: [
    'Glanza',
    'Urban Cruiser',
    'Innova Crysta',
    'Fortuner',
    'Vellfire',
    'Camry',
    'Hilux',
    'Belta',
    'Rumion',
    'New innova Crysta',
  ],
  Honda: [
    'City eHEV',
    'Amaze',
    'All New City',
    'Razz',
    'WR - V',
    'City',
    'HR - V',
    'New Jazz',
  ],
  Mercedes: [
    'New Class - C ',
    'GLC',
    'GLE',
    'GLA',
    'Maybach E - Class',
    'a - Class Limousine',
    'C - Class',
    'GLS',
    'E - Class',
    'EQC',
    'Maybach GLS',
    'AMG E53',
    'AMG A45S',
    'EQB',
    'E - Class Cabriolet Facelift',
    'GLC - Coupe',
    'C - Class Cabriolet',
    'AMG A 35',
    'V- Class',
    'AMG GLC43 Coupe',
    'AMG GLA35',
    'C - COUPE',
    'AMG E63',
    'AMG GLE Coupe',
    'EQS',
    'EQE',
    'AMG GT Black Series',
    'AMG GT 4 - Door Coupe',
    'G - Class',
  ],
  Skoda: ['Salvia', 'Kushaq', 'Octavia', 'Rapid TSI', 'Superb', 'Kodiaq'],
  BMW: [
    'BMW i 4',
    'BMW 3 series',
    'BMW X 1',
    'BMW X 7',
    'BMW Z 4',
    'BMW 2 series Gran Coupe',
    'BMW 5 Series',
    'BMW X 5',
    'BMW X 3',
    'BMW M 8',
    'BMW 6 Series GT',
    'BMW M 5',
    'BMW M 2',
    'BMW iX',
    'BMW 7 Series',
    'BMW 3 Series  Gran Limousine',
    'BMW X 4',
    'BMW 8 Series',
    'BMW X 6',
    'BMW M 4 Competetion',
    'BMW X 5 M',
    'BMW X 8',
  ],
};
